[environments]
  [environments.development]
    name = "radix-github-webhook-dev"
    namespace = "radix-github-webhook-dev"
    wait = true
    watch = false
    watch-delay = 2
    auto-connect = false
    dockerfile = "Dockerfile"
    chart = ""
