apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: radix-github-webhook
spec:
  environments:
  - name: prod
    build:
      from: release
  - name: qa
    build:
      from: master
  components:
  - name: "webhook"
    readOnlyFileSystem: true
    src: "."
    dockerfileName: "Dockerfile"
    ports:
    - name: http
      port: 3001
    publicPort: http
    variables:
      LOG_LEVEL: info
      LOG_PRETTY: "false"
      GIN_MODE: "release"
    environmentConfig:
    - environment: qa
      variables:
        API_SERVER_ENDPOINT_PREFIX: "https://server-radix-api-qa"
      resources:
        requests:
          memory: "30Mi"
          cpu: "10m"
        limits:
          memory: "30Mi"
          cpu: "1000m"
    - environment: prod
      replicas: 2
      variables:
        API_SERVER_ENDPOINT_PREFIX: "https://server-radix-api-prod"
      resources:
        requests:
          memory: "75Mi"
          cpu: "10m"
        limits:
          memory: "75Mi"
          cpu: "1000m"