apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: radix-github-webhook
spec:
  environments:
  - name: prod
    build:
      from: release
  - name: qa
    build:
      from: master
  - name: dev
  components:
  - name: "webhook"
    src: "."
    dockerfileName: "Dockerfile"
    ports:
    - name: http
      port: 3001
    public: true
    environmentConfig:
    - environment: dev
      variables:
        API_SERVER_ENDPOINT_PREFIX: "https://server-radix-api-dev"
    - environment: qa
      variables:
        API_SERVER_ENDPOINT_PREFIX: "https://server-radix-api-qa"
      resources:
        requests:
          memory: "30Mi"
          cpu: "10m"
        limits:
          memory: "60Mi"
          cpu: "50m"
    - environment: prod
      variables:
        API_SERVER_ENDPOINT_PREFIX: "https://server-radix-api-prod"
      resources:
        requests:
          memory: "30Mi"
          cpu: "10m"
        limits:
          memory: "60Mi"
          cpu: "50m"