apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: radix-github-webhook
spec:
  environments:
  - name: prod
  - name: qa
    build:
      from: master
  components:
  - name: "webhook"
    src: "."
    dockerfileName: "Dockerfile"
    ports:
    - name: http
      port: 3001
    public: true
