apiVersion: radix.equinor.com/v1
kind: RadixDeployment
metadata:
  labels:
    radix-commit: {{ .Values.buildID }}
    radix-env: {{ .Values.app.env }}
    radixApp: {{ .Values.app.name }}
    draft: {{ default "draft-app" .Values.draft }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"    
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.namespace }}
spec:
  appname: {{ .Values.app.name }}
  components:
  - environmentVariables:
      API_SERVER_ENDPOINT_PREFIX: "https://server-radix-api-dev"
    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
    name: {{ .Values.component.name }}
    monitoring: true
    ports:
    - name: http
      port: {{ .Values.component.port }}
    public: true
    replicas: 1
  environment: {{ .Values.app.env }}