apiVersion: batch/v1
kind: Job
metadata:
  name: radix-github-init-deploy
  namespace: radix-github-webhook-app
spec:
  backoffLimit: 4
  completions: 1
  parallelism: 1
  template:
    spec:
      serviceAccountName: radix-pipeline
      containers:
      - args:
        - BRANCH=master
        - RADIX_FILE_NAME=/workspace/radixconfig.yaml
        - IMAGE_TAG=latest
        image: radixdev.azurecr.io/radix-pipeline:latest
        name: radix-pipeline-init-api
        volumeMounts:
        - mountPath: /workspace
          name: build-context
      imagePullSecrets:
      - name: radix-docker-v2
      initContainers:
      - args:
        - apk add --no-cache bash openssh-client git && ls /root/.ssh && cd /workspace
          && git clone git@github.com:Statoil/radix-github-webhook.git -b master 
          .
        command:
        - /bin/sh
        - -c
        image: alpine:3.7
        name: clone
        volumeMounts:
        - mountPath: /workspace
          name: build-context
        - mountPath: /root/.ssh
          name: git-ssh-keys
          readOnly: true
      restartPolicy: Never
      volumes:
      - emptyDir: {}
        name: build-context
      - name: git-ssh-keys
        secret:
          defaultMode: 256
          secretName: git-ssh-keys